Repository COVESA/dlt-viewer, pull requests merged in 2024-06, with the labels that each got.

#476 Add tooltips to logs
  src/tablemodel.cpp
Labels: enhancement

#481 Fix dark mode.
  qdlt/qdltfile.cpp
  qdlt/qdltfilterlist.cpp
  src/tablemodel.cpp
Labels: bug

#474 Fixed some compilation warnings
  qdlt/qdltargument.cpp
  qdlt/qdltmsg.cpp
  src/dltexporter.cpp
Labels: enhancement

#484 MacOS build more verbose
  .github/release.yml
  INSTALL.md
  scripts/darwin/build.sh
Labels: Build pipeline

#482 @rpath/libqdlt.dylib fix for MacOS
  .github/workflows/Release.yml
  scripts/darwin/build.sh
  scripts/darwin/install.sh
  src/CMakeLists.txt
Labels: Build pipeline

#485 MacOS qt5 arm64 build
  .github/workflows/BuildPR.yml
  scripts/darwin/build.sh
  scripts/darwin/install.sh
Labels: WIP, macOS, Build pipeline

#493 Fix Multifilter feature, expecially with older Qt version.
  INSTALL.md
  build_config.bat
  src/mainwindow.cpp
  src/mainwindow.h
  src/mainwindow.ui
Labels: bug

#494 Fix filter active color.
  src/mainwindow.cpp
  src/project.cpp
Labels: bug
