Repository COVESA/dlt-viewer, pull requests merged in 2024-10, with the labels that each got.

#553 Improve speed of MF4 and PCAP import.
  qdlt/qdltimporter.cpp
  qdlt/qdltimporter.h
Labels: bug, enhancement

#543 Use QCommandLineParser for command line args parsing
  qdlt/qdltoptmanager.cpp
  qdlt/qdltoptmanager.h
  qdlt/tests/CMakeLists.txt
  qdlt/tests/test_dltoptmanager.cpp
  src/main.cpp
  src/mainwindow.cpp
Labels: enhancement

#554 Enable Filter Regex Replacement also for exporting into DLT format.
  qdlt/qdltexporter.cpp
  qdlt/qdltfile.cpp
  qdlt/qdltfile.h
  qdlt/qdltfilterlist.cpp
  qdlt/qdltfilterlist.h
Labels: enhancement

#555 Fix setting filter index range start and stop when filter are active.
  src/mainwindow.cpp
Labels: bug

#556 Revert/Remove Regex Replace feature for DLT Export.
  qdlt/qdltexporter.cpp
Labels: bug

#559 Rename build file for Darwin
  .github/workflows/BuildPR.yml
  .github/workflows/Release.yml
  scripts/darwin/build_cmake.sh
Labels: Build pipeline

#561 Rename qmake build file for Windows
  build_parser_windows_qt5_MSVC_qmake.bat
  build_sdk_windows_qt5_MSVC_interactive_qmake.bat
  build_sdk_windows_qt5_MSVC_qmake.bat
Labels: Build pipeline

#562 Linux build only with cmake in CI
  scripts/linux/build.sh
Labels: Build pipeline

#565 Fix and Improve RegEx Replace feature.
  qdlt/qdltexporter.cpp
  qdlt/qdltfile.cpp
  qdlt/qdltfile.h
  qdlt/qdltfilterlist.cpp
  qdlt/qdltfilterlist.h
  src/searchtablemodel.cpp
  src/tablemodel.cpp
Labels: bug, enhancement

#564 Add QDltOptmanager unit tests and minor cleanup
  qdlt/qdltexporter.cpp
  qdlt/qdltoptmanager.cpp
  qdlt/qdltoptmanager.h
  qdlt/tests/CMakeLists.txt
  qdlt/tests/test_dltoptmanager.cpp
  src/main.cpp
  src/mainwindow.cpp
Labels: enhancement, merge

#567 Add dlf file extension when saving filter
  src/mainwindow.cpp
Labels: enhancement, merge

#570 Remove CtxId check from Filetransfer Plugin.
  plugin/examples/filetransferplugin_configuration.xml
  plugin/filetransferplugin/configuration.cpp
  plugin/filetransferplugin/configuration.h
  plugin/filetransferplugin/filetransferplugin.cpp
Labels: enhancement

#571 Improve progress output.
  commander/main.cpp
  qdlt/qdltexporter.cpp
  src/dltfileindexer.cpp
  src/mainwindow.cpp
Labels: enhancement

#569 Simplify handling of logging only mode in log table view
  src/tablemodel.cpp
Labels: merge

#566 Reapply "Use QCommandLineParser instead of custom cmd args parsing (#543)"
  qdlt/qdltoptmanager.cpp
  qdlt/qdltoptmanager.h
  qdlt/tests/test_dltoptmanager.cpp
  src/mainwindow.cpp
Labels: help wanted, don't merge

#574 Fix for command line parser issue with multiple arguments with same t…
  qdlt/qdltoptmanager.cpp
Labels: bug
