Repository COVESA/dlt-viewer, pull requests merged in 2024-07, with the labels that each got.

#496 Remove unused code and silence a deprecation warnings
  src/main.cpp
  src/mainwindow.cpp
  src/searchdialog.cpp
  src/searchdialog.h
Labels: enhancement

#497 Fix filter menu.
  src/dltfileindexer.cpp
  src/mainwindow.cpp
Labels: bug

#498 Cleanup commandline output.
  plugin/dltdbusplugin/dltdbusplugin.cpp
  plugin/dltviewerplugin/dltviewerplugin.cpp
  plugin/filetransferplugin/filetransferplugin.cpp
  qdlt/qdltfile.cpp
  qdlt/qdltoptmanager.cpp
  qdlt/qdltpluginmanager.cpp
  src/dltfileindexer.cpp
  src/mainwindow.cpp
  src/mainwindow.h
Labels: enhancement

#504 Fix release job
  .github/workflows/Release.yml
Labels: Build pipeline

#499 Fix more compilation warnings
  qdlt/qdltargument.cpp
  qdlt/qdltimporter.cpp
  qdlt/qdltmsg.cpp
  qdlt/qdltpluginmanager.cpp
  qdlt/qdltpluginmanager.h
  src/plugintreewidget.cpp
  src/plugintreewidget.h
  src/settingsdialog.cpp
Labels: enhancement

#506 Rename dlt_common.c into dlt_common.cpp.
  qdlt/CMakeLists.txt
  qdlt/dlt_common.cpp
  qdlt/qdlt.pro
Labels: enhancement

#512 Revert Rename of dlt_common.
  qdlt/CMakeLists.txt
  qdlt/dlt_common.c
  qdlt/qdlt.pro
  src/mainwindow.cpp
Labels: enhancement
