Repository COVESA/dlt-viewer, pull requests merged in 2024-12, with the labels that each got.

#596 Fix MF4 import with only one datablock.
  qdlt/qdltimporter.cpp
Labels: bug

#598 Prepare v2.27.0 release
  INSTALL.md
  README.md
  ReleaseNotes_Viewer.txt
  src/version.h
Labels: enhancement

#583 Cleanup the code related to ECUs tree populating functionality
  src/dltfileindexer.cpp
  src/dltfileindexer.h
  src/mainwindow.cpp
  src/mainwindow.h
  src/project.cpp
  src/project.h
Labels: enhancement

#586 Fix compilation issues
  CMakeLists.txt
  src/mainwindow.cpp
  src/src.pro
Labels: enhancement

#594 No use of QtGlobal in c-code
  plugin/dlttestrobotplugin/dlttestrobotplugin.cpp
  qdlt/dlt_types.h
  qdlt/dlt_user.h
  qdlt/export_rules.h
  qdlt/qdltsegmentedmsg.h
  src/dltmsgqueue.cpp
  src/mainwindow.cpp
Labels: enhancement, merge

#602 Remove qmake windows build scripts.
  build_sdk_windows_qt5_MSVC_interactive_qmake.bat
  build_sdk_windows_qt5_MSVC_qmake.bat
Labels: enhancement
