Repository COVESA/dlt-viewer, pull requests merged in 2024-09, with the labels that each got.

#521 Mac app store
  INSTALL.md
  README.md
Labels: enhancement

#522 change parent of actions in config context menu
  src/mainwindow.cpp
Labels: bug

#505 Testable search
  BuildDltViewer.pro
  CMakeLists.txt
  qdlt/CMakeLists.txt
  qdlt/dltmessagematcher.cpp
  qdlt/dltmessagematcher.h
  qdlt/qdlt.pro
  qdlt/tests/CMakeLists.txt
  qdlt/tests/test_dltmessagematcher.cpp
  src/searchdialog.cpp
  src/searchdialog.h
  src/src.pro
Labels: enhancement

#519 fix signal for socket error
  src/mainwindow.cpp
Labels: bug

#525 Remove dead code related to payload range search functionality
  src/searchdialog.cpp
  src/searchdialog.h
  src/searchdialog.ui
Labels: enhancement

#530 Increase precision of float ouput to 8 digits
  qdlt/qdltargument.cpp
Labels: enhancement

#528 Keep console logging if app is launched from cmd
  qdlt/qdltoptmanager.cpp
Labels: enhancement

#531 Make code backward compatible with Qt 5.12
  src/mainwindow.cpp
Labels: bug

#532 Notarization (copy)
  .github/workflows/BuildPR.yml
Labels: Build pipeline

#537 Removed creating tar from build
  scripts/darwin/build.sh
Labels: macOS, Build pipeline

#539 Skip notarization on a fork
  .github/workflows/BuildPR.yml
Labels: Build pipeline

#540 Skip notarization on a fork
  .github/workflows/BuildPR.yml
Labels: Build pipeline

#542 Enable Debian build for noble.
  build_viewer_debs_noble.sh
  noble/debian/changelog
  noble/debian/compat
  noble/debian/control
  noble/debian/copyright
  noble/debian/covesa-dlt-viewer-dev.install
  noble/debian/covesa-dlt-viewer.install
  noble/debian/docs
  noble/debian/rules
  noble/debian/source/format
Labels: enhancement

#538 Run unit tests for Linux on CI
  .github/workflows/BuildPR.yml
  qdlt/CMakeLists.txt
  qdlt/tests/CMakeLists.txt
  scripts/linux/build.sh
  scripts/linux/install.sh
Labels: Build pipeline

#544 Fix qmake build
  qdlt/qdlt.pro
Labels: bug

#546 Change regex replace func from std to qt internal.
  qdlt/qdltfilterlist.cpp
  src/regex_search_replace.h
  src/searchtablemodel.cpp
  src/src.pro
  src/tablemodel.cpp
Labels: bug

#548 Fix MacOS release artifacts
  .github/workflows/Release.yml
Labels: Build pipeline

#549 MacOS release with codesign and notarization
  .github/workflows/Release.yml
Labels: Build pipeline

#550 Include mac artifacs release
  .github/workflows/Release.yml
Labels: Build pipeline
