Repository COVESA/dlt-viewer, pull requests merged in 2024-11, with the labels that each got.

#578 Change table view font on Ctrl + Wheel combination
  src/dlttableview.cpp
  src/dlttableview.h
  src/mainwindow.cpp
  src/mainwindow.h
Labels: enhancement, merge

#575 LRU for main table model
  qdlt/CMakeLists.txt
  qdlt/qdltfile.cpp
  qdlt/qdltfile.h
  qdlt/qdltfilter.cpp
  qdlt/qdltfilter.h
  qdlt/qdltfilterlist.cpp
  qdlt/qdltfilterlist.h
  qdlt/qdltlrucache.hpp
  src/tablemodel.cpp
  src/tablemodel.h
Labels: enhancement, merge

#580 Fix wheel scrolling of the main tableview
  src/dlttableview.cpp
Labels: bug, merge

#579 Remove unused mcudpsocket class
  .clang-format
  src/CMakeLists.txt
  src/mcudpsocket.cpp
  src/mcudpsocket.h
  src/project.h
  src/src.pro
Labels: enhancement, merge

#581 Progress output in dlt-commander.
  qdlt/qdltfile.cpp
Labels: enhancement

#582 Background thread for import.
  commander/main.cpp
  qdlt/qdltimporter.cpp
  qdlt/qdltimporter.h
  src/mainwindow.cpp
  src/mainwindow.h
Labels: enhancement, merge

#584 Background thread for export.
  commander/main.cpp
  qdlt/qdltexporter.cpp
  qdlt/qdltexporter.h
  src/mainwindow.cpp
  src/mainwindow.h
Labels: enhancement

#585 Improve speed MF4 import.
  commander/main.cpp
  qdlt/qdltimporter.cpp
Labels: enhancement

#587 Notarization updates
  scripts/darwin/Info.plist.in
  src/resources/icon/icon.icns
Labels: macOS

#589 Remove extra thread for filter index to improve performance.
  src/dltfileindexer.cpp
Labels: enhancement

#591 Multifilter export feature for dlt-commander (-multifilter)
  commander/main.cpp
  commander/optmanager.cpp
  commander/optmanager.h
  qdlt/qdltexporter.cpp
  qdlt/qdltexporter.h
Labels: enhancement

#593 Rename Linux build
  .github/workflows/BuildPR.yml
  .github/workflows/Release.yml
  scripts/linux/build.md
  scripts/linux/buildUbuntu20.sh
  scripts/linux/installUbuntu20.sh
Labels: Build pipeline
