Repository COVESA/dlt-viewer, pull requests merged in 2025-07, with the labels that each got.

#637 Configure Keyboard Shortcuts
  src/mainwindow.cpp
  src/mainwindow.h
  src/mainwindow.ui
Labels: enhancement

#690 Fix regexp replace functionality in commander
  commander/dltfileexporter.cpp
Labels: bug

#662 add cmake presets and update gitignore
  .gitignore
  CMakePresets.json
Labels: merge

#695 Update ReleaseNotes_Viewer.txt
  ReleaseNotes_Viewer.txt
Labels: enhancement

#687 Use Qt 6 for deb packaging
  .github/workflows/BuildPR.yml
  build_viewer_debs_noble.sh
  noble/debian/control
  noble/debian/rules
  plugin/plugin.pri
  scripts/linux/installUbuntu22and24.sh
Labels: Build pipeline

#710 Fix Windows release pipeline
  .github/workflows/BuildPR.yml
  .github/workflows/Release.yml
Labels: Build pipeline

#711 qdlt library already in dlt-viewer debian package
  noble/debian/covesa-dlt-viewer-dev.install
Labels: bug
