Repository COVESA/dlt-viewer, pull requests merged in 2025-08, with the labels that each got.

#712 Fix Noble Debian Packaging.
  focal/debian/changelog
  focal/debian/compat
  focal/debian/control
  focal/debian/copyright
  focal/debian/covesa-dlt-viewer-dev.install
  focal/debian/covesa-dlt-viewer.install
  focal/debian/docs
  focal/debian/rules
  focal/debian/source/format
  noble/debian/covesa-dlt-viewer-dev.install
  noble/debian/covesa-dlt-viewer.install
Labels: enhancement

#716 Fix Debian Build Plugins Path.
  CMakeLists.txt
  noble/debian/rules
  qdlt/CMakeLists.txt
Labels: bug

#719 Keep single pipeline definition for PR and release
  .github/workflows/BuildPR.yml
  .github/workflows/Release.yml
Labels: merge, macOS, Build pipeline
