Repository COVESA/dlt-viewer, pull requests merged in 2025-01, with the labels that each got.

#588 improve mingw compatibility and free the console in additional places
  CMakeLists.txt
  qdlt/qdltoptmanager.cpp
  qdlt/qdltoptmanager.h
  scripts/windows/version.cmake
Labels: enhancement, merge

#613 Update qdltbase.h
  qdlt/qdltbase.h
Labels: bug

#618 Fix incorrect matching algo
  qdlt/dltmessagematcher.cpp
  qdlt/tests/test_dltmessagematcher.cpp
Labels: bug, merge
