Repository COVESA/dlt-viewer, pull requests merged in 2025-02, with the labels that each got.

#615 Remove code duplication when writing dlt message
  qdlt/qdltimporter.cpp
  qdlt/qdltimporter.h
  src/mainwindow.cpp
  src/mainwindow.h
Labels: merge

#623 Select by commandline signature, which columns are exported in CSV.
  commander/main.cpp
  commander/optmanager.cpp
  commander/optmanager.h
  qdlt/qdltexporter.cpp
  qdlt/qdltexporter.h
  qdlt/qdltoptmanager.cpp
  qdlt/qdltoptmanager.h
  src/mainwindow.cpp
Labels: enhancement

#606 Do not block UI when building ECUs tree
  qdlt/CMakeLists.txt
  qdlt/qdlt.pro
  qdlt/qdltctrlmsg.cpp
  qdlt/qdltctrlmsg.h
  qdlt/tests/CMakeLists.txt
  qdlt/tests/test_dltctrlmsg.cpp
  src/CMakeLists.txt
  src/ecutree.cpp
  src/ecutree.h
  src/mainwindow.cpp
  src/mainwindow.h
  src/src.pro
Labels: enhancement, merge

#625 install required offscreen plugin into appimage
  scripts/linux/linuxdeploy.cmake.in
Labels: bug, merge

#628 Document Dependencies for Executing AppImage
  scripts/linux/install.md
Labels: merge

#634 Distinguish Log Generation and Storage Timestamps
  src/mainwindow.cpp
  src/mainwindow.h
  src/tablemodel.cpp
  src/tablemodel.h
Labels: enhancement, merge

#633 Fix performance issue with online tracing.
  src/mainwindow.cpp
Labels: bug

#631 Improve Dark Mode Visibility of Scrollbar
  src/mainwindow.cpp
Labels: enhancement

#629 Mark and Jump To Messages
  src/mainwindow.cpp
  src/mainwindow.h
Labels: enhancement

#630 Copy Message Payload
  src/mainwindow.cpp
  src/mainwindow.h
Labels: enhancement, merge
